name: Post Release Publish Tasks

on:
  release:
    types: [published]

jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml
    with:
      version: ${{ github.event.release.tag_name }}

  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CRYPTOMATOR_DESKTOP }}
          SLACK_USERNAME: 'Cryptobot'
          SLACK_ICON: false
          SLACK_ICON_EMOJI: ':bot:'
          SLACK_CHANNEL: 'cryptomator-desktop'
          SLACK_TITLE: "Release ${{ github.event.repository.name }} ${{ github.event.release.tag_name }} published."
          SLACK_MESSAGE: "Ready to <https://github.com/${{ github.repository }}/actions/workflows/debian.yml|build deb Package>."
          SLACK_FOOTER: false
          MSG_MINIMAL: true

  get-asset-urls:
    name: Get release asset URLs
    runs-on: ubuntu-latest
    outputs:
      msi-url: ${{ steps.urls.outputs.msi }}
      exe-url: ${{ steps.urls.outputs.exe }}
    steps:
      - name: Extract MSI and EXE download URLs
        id: urls
        run: |
          MSI_URL=$(jq -r '[.[] | select(.name | endswith("-x64.msi"))][0].browser_download_url // "null"' <<< "$RELEASE_ASSETS")
          EXE_URL=$(jq -r '[.[] | select(.name | endswith("-x64.exe"))][0].browser_download_url // "null"' <<< "$RELEASE_ASSETS")
          echo "msi=${MSI_URL}" >> $GITHUB_OUTPUT
          echo "exe=${EXE_URL}" >> $GITHUB_OUTPUT
        env:
          RELEASE_ASSETS: ${{ toJson(github.event.release.assets) }}

  allowlist-msi-x64:
    needs: [get-asset-urls]
    if: needs.get-asset-urls.outputs.msi-url != 'null'
    uses: ./.github/workflows/av-whitelist.yml
    with:
      url: ${{ needs.get-asset-urls.outputs.msi-url }}
    secrets: inherit

  allowlist-exe-x64:
    needs: [get-asset-urls, allowlist-msi-x64]
    if: needs.get-asset-urls.outputs.exe-url != 'null'
    uses: ./.github/workflows/av-whitelist.yml
    with:
      url: ${{ needs.get-asset-urls.outputs.exe-url }}
    secrets: inherit

  notify-winget:
    name: Notify for winget-release
    if: needs.get-version.outputs.versionType == 'stable'
    needs: [get-version, get-asset-urls]
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CRYPTOMATOR_DESKTOP }}
          SLACK_USERNAME: 'Cryptobot'
          SLACK_ICON: false
          SLACK_ICON_EMOJI: ':bot:'
          SLACK_CHANNEL: 'cryptomator-desktop'
          SLACK_TITLE: "Release ${{ github.event.repository.name }} ${{ github.event.release.tag_name }} published."
          SLACK_MESSAGE: "Ready to <https://github.com/${{ github.repository }}/actions/workflows/winget.yml|release to winget>."
          SLACK_FOOTER: false
          MSG_MINIMAL: true

  notify-website-repo:
    if: needs.get-version.outputs.versionType == 'stable'
    needs: [get-version]
    runs-on: ubuntu-latest
    steps:
      - name: Notify website repo about desktop update
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          event-type: desktop-update
          token: ${{ secrets.CRYPTOBOT_RELEASE_TOKEN }}
          repository: cryptomator/cryptomator.github.io

